package com.homesoft.springboot.nba_springboot.service;

import com.homesoft.springboot.nba_springboot.dao.ConferenceDAO;
import com.homesoft.springboot.nba_springboot.dao.DivisionDAO;
import com.homesoft.springboot.nba_springboot.dao.PlayerDAO;
import com.homesoft.springboot.nba_springboot.dao.TeamDAO;
import com.homesoft.springboot.nba_springboot.model.Team;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcOperations;
import org.springframework.stereotype.Service;

@Service
public class AutoDataService {

    @Autowired
    private JdbcOperations jdbcOperations;

    @Autowired
    private TeamUpdateService teamUpdateService;

    @Autowired
    private PlayerDAO playerDAO;

    @Autowired
    private TeamDAO teamDAO;

    @Autowired
    private DivisionDAO divisionDAO;

    @Autowired
    private ConferenceDAO conferenceDAO;

    public void clearTable() {
        playerDAO.deleteAll();
        teamDAO.deleteAll();
        divisionDAO.deleteAll();
        conferenceDAO.deleteAll();
    }

    public void resetSeasonResults() {
        teamDAO.findAll().forEach(team -> teamUpdateService.updateTeam(team, 0, 0, 0, team.getTeamId()));
    }

    public void autofillTable() {
        clearTable();
        jdbcOperations.update(
                        "INSERT INTO CONFERENCE (CONFERENCE_ID, CONFERENCE_TITLE) VALUES (1, 'West');" +
                        "INSERT INTO CONFERENCE (CONFERENCE_ID, CONFERENCE_TITLE) VALUES (2, 'East');" +
                        "INSERT INTO DIVISION (DIVISION_ID, DIVISION_TITLE, CONFERENCE_ID) VALUES (1, 'Pacific', 1);" +
                        "INSERT INTO DIVISION (DIVISION_ID, DIVISION_TITLE, CONFERENCE_ID) VALUES (2, 'Northwest', 1);" +
                        "INSERT INTO DIVISION (DIVISION_ID, DIVISION_TITLE, CONFERENCE_ID) VALUES (3, 'Southwest', 1);" +
                        "INSERT INTO DIVISION (DIVISION_ID, DIVISION_TITLE, CONFERENCE_ID) VALUES (4, 'Atlantic', 2);" +
                        "INSERT INTO DIVISION (DIVISION_ID, DIVISION_TITLE, CONFERENCE_ID) VALUES (5, 'Central', 2);" +
                        "INSERT INTO DIVISION (DIVISION_ID, DIVISION_TITLE, CONFERENCE_ID) VALUES (6, 'Southeast', 2);" +
                        "INSERT INTO TEAM (TEAM_ID, TEAM_CITY, TEAM_TITLE, CONFERENCE_ID, DIVISION_ID) VALUES (1, 'Golden State', 'Warriors', 1, 1);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (30, 'Stephen', 'Curry', 1.54, 1.45, 1.49, 1);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (35, 'Kevin', 'Durant', 1.54, 1.68, 1.32, 1);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (11, 'Klay', 'Thompson', 1.53, 1.31, 1.32, 1);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (23, 'Draymond', 'Green', 1.55, 1.67, 1.22, 1);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (15, 'Damian', 'Jones', 1.72, 1.19, 0.0, 1);" +
                        "INSERT INTO TEAM (TEAM_ID, TEAM_CITY, TEAM_TITLE, CONFERENCE_ID, DIVISION_ID) VALUES (2, 'Los Angeles', 'Clippers', 1, 1);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (34, 'Tobias', 'Harris', 1.55, 1.78, 1.42, 2);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (8, 'Danilo', 'Gallinari', 1.42, 1.47, 1.46, 2);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (11, 'Avery', 'Bradley', 1.39, 1.1, 1.24, 2);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (21, 'Patrick', 'Beverley', 1.4, 1.33, 1.31, 2);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (13, 'Marcin', 'Gortat', 1.53, 1.42, 0.0, 2);" +
                        "INSERT INTO TEAM (TEAM_ID, TEAM_CITY, TEAM_TITLE, CONFERENCE_ID, DIVISION_ID) VALUES (3, 'Los Angeles', 'Lakers', 1, 1);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (23, 'LeBron', 'James', 1.57, 1.67, 1.39, 3);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (0, 'Kyle', 'Kuzma', 1.57, 1.41, 1.29, 3);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (14, 'Brandon', 'Ingram', 1.47, 1.37, 1.3, 3);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (7, 'JaVale', 'McGee', 1.62, 1.39, 1.33, 3);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (2, 'Lonzo', 'Ball', 1.43, 1.39, 1.33, 3);" +
                        "INSERT INTO TEAM (TEAM_ID, TEAM_CITY, TEAM_TITLE, CONFERENCE_ID, DIVISION_ID) VALUES (4, 'Phoenix', 'Suns', 1, 1);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (1, 'Devin', 'Booker', 1.49, 1.32, 1.34, 4);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (12, 'T.J.', 'Warren', 1.52, 1.34, 1.46, 4);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (22, 'Deandre', 'Ayton', 1.61, 1.79, 0.0, 4);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (3, 'Trevor', 'Ariza', 1.43, 1.51, 1.34, 4);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (0, 'Isaiah', 'Canaan', 1.48, 1.26, 1.37, 4);" +
                        "INSERT INTO TEAM (TEAM_ID, TEAM_CITY, TEAM_TITLE, CONFERENCE_ID, DIVISION_ID) VALUES (5, 'Sacramento', 'Kings', 1, 1);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (24, 'Buddy', 'Hield', 1.5, 1.44, 1.44, 5);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (5, 'DeAaron', 'Fox', 1.52, 1.34, 1.4, 5);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (0, 'Willie', 'Cauley-Stein', 1.52, 1.62, 1.3, 5);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (88, 'Nemanja', 'Bjelica', 1.53, 1.45, 1.49, 5);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (9, 'Iman', 'Shumpert', 1.5, 1.3, 1.37, 5);" +
                        "INSERT INTO TEAM (TEAM_ID, TEAM_CITY, TEAM_TITLE, CONFERENCE_ID, DIVISION_ID) VALUES (6, 'Denver', 'Nuggets', 1, 2);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (15, 'Nikola', 'Jokic', 1.56, 1.75, 1.37, 6);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (14, 'Gary', 'Harris', 1.5, 1.26, 1.34, 6);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (27, 'Jamal', 'Murray', 1.5, 1.34, 1.29, 6);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (4, 'Paul', 'Millsap', 1.49, 1.46, 1.34, 6);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (3, 'Torrey', 'Craig', 1.65, 1.7, 1.19, 6);" +
                        "INSERT INTO TEAM (TEAM_ID, TEAM_CITY, TEAM_TITLE, CONFERENCE_ID, DIVISION_ID) VALUES (7, 'Minnesota', 'Timberwolves', 1, 2);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (32, 'Karl-Anthony', 'Towns', 1.5, 1.92, 1.44, 7);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (22, 'Andrew', 'Wiggins', 1.4, 1.34, 1.4, 7);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (0, 'Jeff', 'Teague', 1.4, 1.22, 1.37, 7);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (67, 'Taj', 'Gibson', 1.53, 1.37, 1.52, 7);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (25, 'Derrick', 'Rose', 1.46, 1.29, 1.46, 7);" +
                        "INSERT INTO TEAM (TEAM_ID, TEAM_CITY, TEAM_TITLE, CONFERENCE_ID, DIVISION_ID) VALUES (8, 'Oklahoma City', 'Thunder', 1, 2);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (0, 'Russel', 'Westbrook', 1.55, 1.78, 1.3, 8);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (13, 'Paul', 'George', 1.47, 1.68, 1.34, 8);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (12, 'Steven', 'Adams', 1.61, 1.55, 0.0, 8);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (9, 'Jerami', 'Grant', 1.54, 1.41, 1.35, 8);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (23, 'Terrance', 'Ferguson', 1.56, 1.14, 1.25, 8);" +
                        "INSERT INTO TEAM (TEAM_ID, TEAM_CITY, TEAM_TITLE, CONFERENCE_ID, DIVISION_ID) VALUES (9, 'Portland', 'Trail Blazers', 1, 2);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (0, 'Damian', 'Lillard', 1.49, 1.44, 1.35, 9);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (3, 'C.J.', 'McCollum', 1.51, 1.28, 1.36, 9);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (27, 'Jusuf', 'Nurkic', 1.56, 1.69, 1.12, 9);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (8, 'Al-Farouq', 'Aminu', 1.46, 1.71, 1.37, 9);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (10, 'Jake', 'Layman', 1.64, 1.18, 1.42, 9);" +
                        "INSERT INTO TEAM (TEAM_ID, TEAM_CITY, TEAM_TITLE, CONFERENCE_ID, DIVISION_ID) VALUES (10, 'Utah', 'Jazz', 1, 2);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (45, 'Donovan', 'Mitchell', 1.48, 1.22, 1.29, 10);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (27, 'Rudy', 'Gobert', 1.7, 1.92, 0.0, 10);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (2, 'Joe', 'Ingles', 1.53, 1.36, 1.38, 10);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (3, 'Ricky', 'Rubio', 1.41, 1.3, 1.33, 10);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (15, 'Derrick', 'Favors', 1.62, 1.39, 1.31, 10);" +
                        "INSERT INTO TEAM (TEAM_ID, TEAM_CITY, TEAM_TITLE, CONFERENCE_ID, DIVISION_ID) VALUES (11, 'Dallas', 'Mavericks', 1, 3);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (77, 'Luka', 'Doncic', 1.51, 1.58, 1.37, 11);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (23, 'Wesley', 'Matthews', 1.49, 1.21, 1.38, 11);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (40, 'Harrison', 'Barners', 1.43, 1.42, 1.32, 11);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (1, 'Dennis', 'Smith Jr.', 1.46, 1.22, 1.39, 11);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (6, 'DeAndre', 'Jordan', 1.61, 2.1, 0, 11);" +
                        "INSERT INTO TEAM (TEAM_ID, TEAM_CITY, TEAM_TITLE, CONFERENCE_ID, DIVISION_ID) VALUES (12, 'Houston', 'Rockets', 1, 3);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (13, 'James', 'Harden', 1.52, 1.48, 1.35, 12);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (3, 'Chris', 'Paul', 1.46, 1.45, 1.39, 12);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (15, 'Clint', 'Capela', 1.62, 1.69, 0, 12);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (17, 'P.J.', 'Tucker', 1.45, 1.7, 1.44, 12);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (8, 'James', 'Ennis', 1.6, 1.13, 1.38, 12);" +
                        "INSERT INTO TEAM (TEAM_ID, TEAM_CITY, TEAM_TITLE, CONFERENCE_ID, DIVISION_ID) VALUES (13, 'Memphis', 'Grizzlies', 1, 3);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (11, 'Mike', 'Conley', 1.45, 1.28, 1.34, 13);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (33, 'Marc', 'Gasol', 1.47, 1.8, 1.41, 13);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (13, 'Jaren', 'Jackson Jr.', 1.56, 1.31, 1.23, 13);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (17, 'Garrett', 'Temple', 1.5, 1.33, 1.43, 13);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (1, 'Kyle', 'Anderson', 1.45, 1.53, 1.14, 13);" +
                        "INSERT INTO TEAM (TEAM_ID, TEAM_CITY, TEAM_TITLE, CONFERENCE_ID, DIVISION_ID) VALUES (14, 'New Orleans', 'Pelicans', 1, 3);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (23, 'Anthony', 'Davis', 1.5, 1.89, 1.35, 14);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (11, 'Jrue', 'Holiday', 1.55, 1.33, 1.28, 14);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (3, 'Nikola', 'Mirotic', 1.6, 1.89, 1.34, 14);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (55, 'ETwaun', 'Moore', 1.6, 1.15, 1.49, 14);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (33, 'Wesley', 'Johnson', 1.55, 1.23, 1.46, 14);" +
                        "INSERT INTO TEAM (TEAM_ID, TEAM_CITY, TEAM_TITLE, CONFERENCE_ID, DIVISION_ID) VALUES (15, 'San Antonio', 'Spurs', 1, 3);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (10, 'DeMar', 'DeRozan', 1.51, 1.54, 1.17, 15);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (12, 'LaMarcus', 'Aldridge', 1.42, 1.75, 0, 15);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (22, 'Rudy', 'Gay', 1.49, 1.58, 1.48, 15);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (11, 'Bryn', 'Forbes', 1.42, 1.14, 1.47, 15);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (33, 'Dante', 'Cunningham', 1.45, 1.29, 1.5, 15);" +
                        "INSERT INTO TEAM (TEAM_ID, TEAM_CITY, TEAM_TITLE, CONFERENCE_ID, DIVISION_ID) VALUES (16, 'Boston', 'Celtics', 2, 4);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (11, 'Kyrie', 'Irving', 1.55, 1.39, 1.39, 16);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (0, 'Jayson', 'Tatum', 1.45, 1.55, 1.38, 16);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (42, 'Al', 'Horford', 1.58, 1.46, 1.29, 16);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (7, 'Jaylen', 'Brown', 1.43, 1.29, 1.27, 16);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (20, 'Gordon', 'Hayward', 1.46, 1.44, 1.28, 16);" +
                        "INSERT INTO TEAM (TEAM_ID, TEAM_CITY, TEAM_TITLE, CONFERENCE_ID, DIVISION_ID) VALUES (17, 'Brooklyn', 'Nets', 2, 4);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (22, 'Caris', 'LeVert', 1.54, 1.33, 1.31, 17);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (1, 'DAngelo', 'Russel', 1.43, 1.29, 1.4, 17);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (12, 'Joe', 'Harris', 1.54, 1.26, 1.5, 17);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (31, 'Jarrett', 'Allen', 1.62, 1.55, 1.2, 17);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (6, 'Jared', 'Dudley', 1.5, 1.24, 1.33, 17);" +
                        "INSERT INTO TEAM (TEAM_ID, TEAM_CITY, TEAM_TITLE, CONFERENCE_ID, DIVISION_ID) VALUES (18, 'New York', 'Knicks', 2, 4);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (3, 'Tim', 'Hardaway Jr.', 1.47, 1.32, 1.36, 18);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (21, 'Damyean', 'Dotson', 1.51, 1.37, 1.32, 18);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (32, 'Noah', 'Vonleh', 1.5, 1.59, 1.3, 18);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (11, 'Frank', 'Ntilikina', 1.4, 1.18, 1.26, 18);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (26, 'Mitchell', 'Robinson', 1.6, 1.2, 0, 18);" +
                        "INSERT INTO TEAM (TEAM_ID, TEAM_CITY, TEAM_TITLE, CONFERENCE_ID, DIVISION_ID) VALUES (19, 'Philadelphia', '76ers', 2, 4);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (21, 'Joel', 'Embiid', 1.5, 2.09, 1.31, 19);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (25, 'Ben', 'Simmons', 1.54, 1.72, 0, 19);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (23, 'Jimmy', 'Butler', 1.57, 1.37, 1.42, 19);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (20, 'Markelle', 'Fultz', 1.43, 1.23, 1.28, 19);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (22, 'Wilson', 'Chandler', 1.6, 1.28, 1.35, 19);" +
                        "INSERT INTO TEAM (TEAM_ID, TEAM_CITY, TEAM_TITLE, CONFERENCE_ID, DIVISION_ID) VALUES (20, 'Toronto', 'Raptors', 2, 4);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (2, 'Kawhi', 'Leonard', 1.5, 1.71, 1.34, 20);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (9, 'Serge', 'Ibaka', 1.62, 1.56, 1.32, 20);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (7, 'Kyle', 'Lowry', 1.59, 1.36, 1.34, 20);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (43, 'Pascal', 'Siakim', 1.68, 1.52, 1.31, 20);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (14, 'Danny', 'Green', 1.45, 1.32, 1.46, 20);" +
                        "INSERT INTO TEAM (TEAM_ID, TEAM_CITY, TEAM_TITLE, CONFERENCE_ID, DIVISION_ID) VALUES (21, 'Chicago', 'Bulls', 2, 5);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (8, 'Zach', 'LaVine', 1.48, 1.51, 1.31, 21);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (2, 'Jabari', 'Parker', 1.48, 1.56, 1.3, 21);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (7, 'Justin', 'Holiday', 1.45, 1.34, 1.4, 21);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (34, 'Wendell', 'Carter Jr.', 1.48, 1.52, 1.03, 21);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (22, 'Cameron', 'Payne', 1.44, 1.13, 1.3, 21);" +
                        "INSERT INTO TEAM (TEAM_ID, TEAM_CITY, TEAM_TITLE, CONFERENCE_ID, DIVISION_ID) VALUES (22, 'Cleveland', 'Cavaliers', 2, 5);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (2, 'Collin', 'Sexton', 1.43, 1.19, 1.52, 22);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (1, 'Rodney', 'Hood', 1.45, 1.22, 1.41, 22);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (3, 'George', 'Hill', 1.58, 1.11, 1.48, 22);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (16, 'Cedi', 'Osman', 1.4, 1.39, 1.31, 22);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (13, 'Tristan', 'Thompson', 1.54, 1.61, 0, 22);" +
                        "INSERT INTO TEAM (TEAM_ID, TEAM_CITY, TEAM_TITLE, CONFERENCE_ID, DIVISION_ID) VALUES (23, 'Detroit', 'Pistons', 2, 5);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (23, 'Blake', 'Griffin', 1.51, 1.87, 1.37, 23);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (0, 'Andre', 'Drummond', 1.53, 2.01, 1.16, 23);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (1, 'Reggie', 'Jackson', 1.44, 1.18, 1.31, 23);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (25, 'Reggie', 'Bullock', 1.39, 1.18, 1.35, 23);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (7, 'Stanley', 'Johnson', 1.5, 1.36, 1.29, 23);" +
                        "INSERT INTO TEAM (TEAM_ID, TEAM_CITY, TEAM_TITLE, CONFERENCE_ID, DIVISION_ID) VALUES (24, 'Indiana', 'Pacers', 2, 5);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (4, 'Victor', 'Oladipo', 1.49, 1.61, 1.34, 24);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (44, 'Bojan', 'Bogdanovic', 1.53, 1.35, 1.53, 24);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (33, 'Myles', 'Turner', 1.5, 1.41, 1.23, 24);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (21, 'Thaddeus', 'Young', 1.54, 1.36, 1.15, 24);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (2, 'Darren', 'Collison', 1.47, 1.18, 1.37, 24);" +
                        "INSERT INTO TEAM (TEAM_ID, TEAM_CITY, TEAM_TITLE, CONFERENCE_ID, DIVISION_ID) VALUES (25, 'Milwaukee', 'Bucks', 2, 5);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (34, 'Giannis', 'Antetokounmpo', 1.62, 2.01, 1.1, 25);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (22, 'Khris', 'Middleton', 1.48, 1.48, 1.42, 25);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (6, 'Eric', 'Bledsoe', 1.59, 1.34, 1.36, 25);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (13, 'Malcolm', 'Brogdon', 1.51, 1.33, 1.42, 25);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (11, 'Brook', 'Lopez', 1.56, 1.33, 1.41, 25);" +
                        "INSERT INTO TEAM (TEAM_ID, TEAM_CITY, TEAM_TITLE, CONFERENCE_ID, DIVISION_ID) VALUES (26, 'Atlanta', 'Hawks', 2, 6);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (11, 'Trae', 'Young', 1.48, 1.26, 1.24, 26);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (12, 'Taurean', 'Prince', 1.51, 1.45, 1.36, 26);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (24, 'Kent', 'Bazemore', 1.55, 1.35, 1.32, 26);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (25, 'Alex', 'Len', 1.55, 1.38, 1.3, 26);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (15, 'Vince', 'Carter', 1.5, 1.21, 1.38, 26);" +
                        "INSERT INTO TEAM (TEAM_ID, TEAM_CITY, TEAM_TITLE, CONFERENCE_ID, DIVISION_ID) VALUES (27, 'Charlotte', 'Hornets', 2, 6);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (15, 'Kemba', 'Walker', 1.53, 1.41, 1.38, 27);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (3, 'Jeremy', 'Lamb', 1.49, 1.43, 1.34, 27);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (40, 'Cody', 'Zeller', 1.57, 1.39, 1.33, 27);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (5, 'Nicolas', 'Batum', 1.47, 1.46, 1.38, 27);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (2, 'Marvin', 'Williams', 1.56, 1.38, 1.28, 27);" +
                        "INSERT INTO TEAM (TEAM_ID, TEAM_CITY, TEAM_TITLE, CONFERENCE_ID, DIVISION_ID) VALUES (28, 'Miami', 'Heat', 2, 6);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (0, 'Josh', 'Richardson', 1.44, 1.31, 1.44, 28);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (7, 'Goran', 'Dragic', 1.18, 1.27, 1.32, 28);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (21, 'Hassan', 'Whiteside', 1.51, 2.06, 1.18, 28);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (17, 'Rodney', 'McGruder', 1.48, 1.43, 1.42, 28);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (20, 'Justise', 'Winslow', 1.36, 1.41, 1.26, 28);" +
                        "INSERT INTO TEAM (TEAM_ID, TEAM_CITY, TEAM_TITLE, CONFERENCE_ID, DIVISION_ID) VALUES (29, 'Orlando', 'Magic', 2, 6);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (9, 'Nikola', 'Vucevic', 1.57, 1.81, 1.45, 29);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (0, 'Aaron', 'Gordon', 1.55, 1.56, 1.37, 29);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (10, 'Evan', 'Fournier', 1.53, 1.26, 1.29, 29);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (14, 'D.J.', 'Augustin', 1.45, 1.16, 1.46, 29);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (1, 'Jonathan', 'Isaac', 1.54, 1.4, 1.29, 29);" +
                        "INSERT INTO TEAM (TEAM_ID, TEAM_CITY, TEAM_TITLE, CONFERENCE_ID, DIVISION_ID) VALUES (30, 'Washington', 'Wizards', 2, 6);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (3, 'Bradley', 'Beal', 1.55, 1.41, 1.33, 30);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (2, 'John', 'Wall', 1.49, 1.27, 1.32, 30);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (21, 'Dwight', 'Howard', 1.62, 1.66, 0, 30);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (22, 'Otto', 'Porter Jr.', 1.53, 1.37, 1.36, 30);" +
                        "INSERT INTO PLAYER (PLAYER_NUMBER, PLAYER_FIRST_NAME, PLAYER_LAST_NAME, PLAYER_ATTACK_RATE, PLAYER_DEFENCE_RATE, PLAYER_THREE_POINT_RATE, TEAM_ID) VALUES (5, 'Markieff', 'Morris', 1.5, 1.35, 1.34, 30);"
        );
    }
}
